Repository sadanandpai/resume-builder, pull requests merged in 2022-04, with the labels that each got.

#66 fix: :lipstick: prepend test
  src/__test__/index.test.tsx
  src/pages/_app.tsx
Labels: bug

#67 MUI global theme color overridden
  src/helpers/constants/index.interface.ts
  src/helpers/constants/index.ts
  src/modules/builder/nav-bar/NavBarLayout.tsx
  src/modules/builder/nav-bar/atoms/StyledButton.tsx
  src/modules/builder/nav-bar/atoms/index.ts
  src/modules/builder/nav-bar/components/MenuItem.interface.ts
  src/modules/builder/nav-bar/components/MenuItem.tsx
  src/modules/builder/nav-bar/components/NavMenuPopover.interface.ts
  src/modules/builder/nav-bar/components/NavMenuPopover.tsx
  src/modules/builder/nav-bar/components/ThemeSelect.tsx
  src/styles/global.theme.ts
Labels: version 2

#68 Template selection layout
  package.json
  src/helpers/constants/index.ts
  src/modules/builder/nav-bar/NavBarLayout.tsx
  src/modules/builder/nav-bar/components/TemplateSelect.tsx
  src/modules/builder/nav-bar/components/TemplatesSlider.tsx
  src/modules/builder/nav-bar/components/ThemeSelect.tsx
Labels: version 2

#70 Extend drag to full pill, center delete image
  src/modules/builder/editor/modules/skills/atoms/SkillPill.tsx
Labels: enhancement
