Repository sadanandpai/resume-builder, pull requests merged in 2022-05, with the labels that each got.

#73 Experience section layout
  package.json
  public/icons/delete.svg
  public/icons/down-arrow.svg
  public/icons/dropdown-arrow.svg
  public/icons/up-arrow.svg
  src/helpers/common/atoms/Switch.tsx
  src/helpers/common/components/MoveEditSectionContainer.tsx
  src/modules/builder/editor/modules/experience/ExperienceLayout.tsx
  src/modules/builder/editor/modules/experience/components/AddExperience.tsx
  src/modules/builder/editor/modules/experience/components/Experience.tsx
  src/modules/builder/nav-bar/components/MenuItem.tsx
  src/pages/_app.tsx
  src/stores/experience.interface.ts
  src/stores/experience.ts
  src/styles/global.theme.ts
Labels: version 2

#76 Education layout integration with template section
  src/helpers/common/components/ErrorBoundary.tsx
  src/helpers/constants/resume-data.json
  src/modules/builder/editor/EditorLayout.tsx
  src/modules/builder/editor/modules/education/components/Education.tsx
  src/modules/builder/editor/modules/experience/components/Experience.tsx
  src/stores/education.interface.ts
  src/stores/experience.interface.ts
  src/stores/index.interface.ts
  src/stores/useResumeStore.tsx
  src/templates/modern/components/Education.tsx
  src/templates/modern/components/Work.tsx
Labels: bug, enhancement, version 2

#79 Home page
  package.json
  public/icons/code-extra-icon.svg
  public/icons/delete.svg
  public/icons/full-screen.svg
  public/icons/github.svg
  public/icons/linkedin.svg
  public/icons/lock.svg
  public/icons/magic.svg
  public/icons/palette.svg
  public/icons/resume-icon.png
  public/icons/resume-icon.svg
  public/icons/right-arrow.svg
  public/icons/speed.svg
  public/icons/style.svg
  public/icons/terminal.svg
  public/icons/wave.svg
  public/resume.png
  src/modules/builder/editor/EditorLayout.tsx
  src/modules/builder/nav-bar/NavBarLayout.tsx
  src/modules/home/HomeLayout.tsx
  src/modules/home/components/FeatureCard.jsx
  src/modules/home/components/PersonCard.jsx
  src/pages/_document.tsx
  src/pages/builder.tsx
  src/pages/index.tsx
  tailwind.config.js
  yarn.lock
Labels: enhancement
